Exits early if SPEL_CI or SPEL_VERSION are not set

diff --git a/build/vagrant/Makefile b/build/vagrant/Makefile
--- a/build/vagrant/Makefile
+++ b/build/vagrant/Makefile
@@ -1,5 +1,5 @@
 SHELL := /bin/bash
-SOURCE_CIDR := $(shell curl 'https://api.ipify.org')/32
+SOURCE_CIDR := $(shell curl -sSL 'https://api.ipify.org')/32
 
 PACKER_VERSION ?= $(shell grep 'FROM hashicorp/packer' Dockerfile 2> /dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' 2> /dev/null)
 PACKER_URL ?= https://releases.hashicorp.com/packer/$(PACKER_VERSION)/packer_$(PACKER_VERSION)_linux_amd64.zip
@@ -12,6 +12,20 @@ TERRAFORM_URL ?= https://releases.hashicorp.com/terraform/$(TERRAFORM_VERSION)/t
 all: build
 
 install:
+	@ if [[ \
+		"$(SPEL_CI)" != "true" && \
+		-z "$(SPEL_VERSION)" \
+	]] ; then \
+		echo "[make]: Must set one of SPEL_VERSION, or SPEL_CI=true!" >&2 ;\
+		exit 1 ;\
+	fi
+	@ if [[ \
+		"$(SPEL_CI)" == "true" && \
+		-n "$(SPEL_VERSION)" \
+	]] ; then \
+		echo "[make]: Can't set both SPEL_VERSION, and SPEL_CI=true!" >&2 ;\
+		exit 1 ;\
+	fi
 	go mod init spel-vagrant
 	go build ./...
 	go mod tidy
